mybatis:
  type-aliases-package: com.by.model
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: cloud-a
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.62.236:3306/cloud
    username: root
    password: 123456

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

server:
  port: 8099

data:
  data: 2023
  location: beijing


#
#logging:
#  level:
#    root: info
#  file:
#    name: /home/logs/cloud.log
#  pattern:
#    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger{50}- %msg%n"
#    file: "%d{yyyy/MM/dd-HH:mm:ss} ---- [%thread] %-5level %logger{50}- %msg%n"
